version: "1.1"
services:
  ServiceApacheAppMiguelCintron2:
    image: php:8.0-apache
    container_name: ApacheAppMiguelCintron2
    networks:
      - Network2MiguelCintron
    ports:
      - "8081:80"
    volumes:
      - ./Modulo2MiguelCintron-2/chocolux-html:/var/www/html
  ServiceMySQLMiguelCintron2:
    image: mysql:8.0
    container_name: MySQLMiguelCintron2
    networks:
      - Network2MiguelCintron
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=M1gu3L
networks:
  Network2MiguelCintron:
    name: Network2MiguelCintron
    driver: bridge